module.exports = {
  populate: async function (req, res) {
    await Task.createEach([
      {
        name: "Rick Sanchez",
        status: "Alive",
        gender: "Male",
        origin: "Earth (C-137)",
        location: "Citadel of Ricks",
        species: "Human",
      },
      {
        name: "Morty Smith",
        status: "Alive",
        gender: "Male",
        origin: "unknown",
        location: "Citadel of Ricks",
        species: "Human",
      },
      {
        name: "Summer Smith",
        status: "Alive",
        gender: "Female",
        origin: "Earth (Replacement Dimension)",
        location: "Earth (Replacement Dimension)",
        species: "Human",
      },
      {
        name: "Beth Smith",
        status: "Alive",
        gender: "Female",
        origin: "Earth (Replacement Dimension)",
        location: "Earth (Replacement Dimension)",
        species: "Human",
      },
      {
        name: "Jerry Smith",
        status: "Alive",
        gender: "Male",
        origin: "Earth (Replacement Dimension)",
        location: "Earth (Replacement Dimension)",
        species: "Human",
      },
      {
        name: "Abadango Cluster Princess",
        status: "Alive",
        gender: "Female",
        origin: "Abadango",
        location: "Abadango",
        species: "Alien",
      },
      {
        name: "Abradolf Lincler",
        status: "unknown",
        gender: "Male",
        origin: "Earth (Replacement Dimension)",
        location: "Testicle Monster Dimension",
        species: "Human",
      },
      {
        name: "Adjudicator Rick",
        status: "Dead",
        gender: "Male",
        origin: "unknown",
        location: "Citadel of Ricks",
        species: "Human",
      },
      {
        name: "Agency Director",
        status: "Dead",
        gender: "Male",
        origin: "Earth (Replacement Dimension)",
        location: "Earth (Replacement Dimension)",
        species: "Human",
      },
      {
        name: "Alan Rails",
        status: "Dead",
        gender: "Male",
        origin: "unknown",
        location: "Worldender's lair",
        species: "Human",
      },
      {
        name: "Albert Einstein",
        status: "Dead",
        gender: "Male",
        origin: "Earth (C-137)",
        location: "Earth (Replacement Dimension)",
        species: "Human",
      },
      {
        name: "Alexander",
        status: "Dead",
        gender: "Male",
        origin: "Earth (C-137)",
        location: "Anatomy Park",
        species: "Human",
      },
      {
        name: "Alien Googah",
        status: "unknown",
        gender: "unknown",
        origin: "unknown",
        location: "Earth (Replacement Dimension)",
        species: "Alien",
      },
      {
        name: "Alien Morty",
        status: "unknown",
        gender: "Male",
        origin: "unknown",
        location: "Citadel of Ricks",
        species: "Alien",
      },
      {
        name: "Alien Rick",
        status: "unknown",
        gender: "Male",
        origin: "unknown",
        location: "Citadel of Ricks",
        species: "Alien",
      },
      {
        name: "Amish Cyborg",
        status: "Dead",
        gender: "Male",
        origin: "unknown",
        location: "Earth (Replacement Dimension)",
        species: "Alien",
      },
      {
        name: "Annie",
        status: "Alive",
        gender: "Female",
        origin: "Earth (C-137)",
        location: "Anatomy Park",
        species: "Human",
      },
      {
        name: "Antenna Morty",
        status: "Alive",
        gender: "Male",
        origin: "unknown",
        location: "Citadel of Ricks",
        species: "Human",
      },
      {
        name: "Antenna Rick",
        status: "unknown",
        gender: "Male",
        origin: "unknown",
        location: "unknown",
        species: "Human",
      },
      {
        name: "Ants in my Eyes Johnson",
        status: "unknown",
        gender: "Male",
        origin: "unknown",
        location: "Interdimensional Cable",
        species: "Human",
      },
    ]);

    return res.json({ ok: "ok" });
  },
};
